services:
  - type: web
    name: OHCards-YearEndParty
    runtime: node
    buildCommand: npm ci
    startCommand: npm start
    healthCheckPath: /api/health
    plan: free
    region: singapore
    envVars:
      - key: NODE_ENV
        value: production
      - key: RENDER_EXTERNAL_URL
        fromService:
          type: web
          name: OHCards-YearEndParty
          property: url
